Introduce Zoom Meeting Component XBlock [EDLY-6408]
edly-io/zoom-meeting-xblock pull request #2
Opened 2024-02-21 08:32 UTC by mfarhan943

**Description:**
Introducing Zoom Meeting Component XBlock, integrating Zoom meeting functionalities directly into the course environment. This enhancement enables users to easily participate in Zoom meetings from within their learning platform, streamlining the process and enriching the educational experience. 

**Jira**
https://edlyio.atlassian.net/browse/EDLY-6408

2024-02-22 11:57 UTC, ziafazal requested changes
@mfarhan943 I have few suggestions.

2024-02-22 12:28 UTC, mfarhan943 commented on zoom_meeting/zoom_meeting.py
> +            "public/lib/react.min.js",
public dir have been added.

2024-02-23 10:55 UTC, mfarhan943 commented on setup.py
> +    license='UNKNOWN',          # TODO: choose a license: 'AGPL v3' and 'Apache 2.0' are popular.
Updated

2024-02-23 10:56 UTC, mfarhan943 commented on README.md
> +ZOOM_MEETING_SDK_KEY: 'zoom-sdk-key or zoom-client-id'
Removed.

2024-03-04 08:08 UTC, ziafazal requested changes
@mfarhan943 completed second round of review.

2024-03-04 08:08 UTC, ziafazal commented on zoom_meeting/zoom_meeting.py
> +        token = jwt.encode(payload, self.sdk_secret, algorithm="HS256")
can we pick this from `JWT_ALGORITHM` key of `JWT_AUTH` setting?

2024-03-04 08:08 UTC, ziafazal commented on zoom_meeting/static/js/src/zoom_meeting.js
> +    var errorDiv = document.createElement("div");
We are using vanila JS and jQuery both in this javascript file. I think we should stick to jquery API only. so far instance here we can create div like this `var errorDiv = $('<div></div>')`

same thing apply to this `document.body.appendChild(errorDiv);` line which can be rewritten like this `$('body').append(errorDiv)`

2024-03-04 08:14 UTC, mfarhan943 commented on zoom_meeting/zoom_meeting.py
> +    def author_view(self, context=None):
The libraries used by zoom aren't correctly loading in studio, so it is functional only in LMS view.

2024-03-04 10:29 UTC, mfarhan943 commented on zoom_meeting/static/js/src/zoom_meeting.js
> +    var errorDiv = document.createElement("div");
Done

2024-03-04 10:54 UTC, ziafazal approved these changes
LGTM 👍

2024-03-04 10:54 UTC, ziafazal commented on zoom_meeting/static/js/src/zoom_meeting.js
> +    console.log('zxaa ', meetingSDKElement)
what is purpose of this console log?

2024-03-04 14:24 UTC, merged